version: '3.7'

services:
    mongo:
      image: mongo
      environment:
          MONGO_INITDB_ROOT_USERNAME: usr
          MONGO_INITDB_ROOT_PASSWORD: pass
          MONGO_INITDB_DATABASE: search-challenge
      ports:
          - 27017:27017
      volumes:
          - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    api:
      build: ./search-challenge-api
      ports:
        - "3001:3001"
      links:
        - "mongo:docker-alias"
      depends_on:
        - mongo

    web:
      build: ./search-challenge-web
      ports:
        - "3000:3000"
      depends_on:
        - api    